#Welcome to Numpy Tutorial.
This is a simple guide for those willing to learn the basics of Numpy for exploratory data analysis in machine learning. This is a quick recap module for getting started.





#Numpy - Numerical Python
It is a popular python library written in C to make calculation process easier and faster for large multi-dimensional arrays and matrices.


In [ ]:
#Simple way to create numPy arrayS:
import numpy as np
a = np.array(20)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a)
print(b)
print(c)
print(d)
arr = np.array([[1, 2, 3, 4], [2,3,4,5]], ndmin=4)
print(arr)

#Indexing is also similar to c++ and python list:

arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr1[0, 1, 2])

20
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[[1 2 3 4]
   [2 3 4 5]]]]
6


#Creating Arrays (1d)
1. From Python List: [1,2,3,4]
2. From Python Tuple: (1, 2,3,4)
3. fromiter() function

In [ ]:
import numpy as np

li = [1, 2, 3, 4]
print(np.array(li))

# create a NumPy array from a tuple
tup = (5, 6, 7, 8)
print(np.array(tup))

# create a NumPy array using fromiter()
iterable = (a for a in range(8))
print(np.fromiter(iterable, float))

[1 2 3 4]
[5 6 7 8]
[0. 1. 2. 3. 4. 5. 6. 7.]


#Creating MultiDimensional Array:
1. From Python List
2. Using empty()

In [ ]:
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]
print(np.array([list_1, list_2, list_3]))

# create a NumPy array using numpy.empty()
print(np.empty([4, 3], int))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#2. Initial Placeholders:
1-d array: arange(start, stop), linespace(start, stop, interval), zeros(val), ones(val), random.rand(val). <br>
2-d array: zeros([3,4], int(float is default)), ones([4,3], int), full([2,2], 67, int), eye(val)

In [ ]:
# create a NumPy array using numpy.arange()
print(np.arange(1, 10))

# create a NumPy array using numpy.linspace()
print(np.linspace(1, 10, 3))

# create a NumPy array using numpy.zeros()
print(np.zeros(5, dtype=int))

# create a NumPy array using numpy.ones()
print(np.ones(5, dtype=int))

# create a NumPy array using numpy.random.rand()
print(np.random.rand(5))

# create a NumPy array using numpy.random.randint()
print(np.random.randint(5, size=10))
# create a NumPy array using numpy.zeros()
print(np.zeros([4, 3], dtype = np.int32))

# create a NumPy array using numpy.ones()
print(np.ones([4, 3], dtype = np.int32))

# create a NumPy array using numpy.full()
print(np.full([2, 2], 67, dtype = int))

# create a NumPy array using numpy.eye()
print(np.eye(4))

[1 2 3 4 5 6 7 8 9]
[ 1.   5.5 10. ]
[0 0 0 0 0]
[1 1 1 1 1]
[0.48042523 0.52333029 0.51053248 0.01340466 0.08154599]
[4 2 4 3 1 2 4 2 1 3]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[67 67]
 [67 67]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#3. Properties:
size, len(arr), shape, dtype, tolist()(array to list).
<br>
 (Array are homogeneous: all same type, List are heterogeneous: different types allowed)

#4. File Loading and Saving
Check back later


#5. Arrays

* Array in numpy is called ndarray. Array are continuous unlike lists.

* Sorting: <br>
1-d: sort() <br>
2-d: sort(arr, axis=val)
Manipulations:

*   append(val): Adds the end of the list 1d.
*   insert(arr, value, index): Inserts value 1d.
*   insert(arr, val, index, axis=0): Insertion 2D.
*   delete(arr, val): Deletes an element 1d.
*   delete(arr, val, axis=0): Deletes first row from 2d.
*  reshape(n, m): Reshaping the 1D array to a 2D array
*  reshape((value)): Reshaping the 2D array to a 1D array
*  resize(n, m): Changing row and column size.
*   sliceing: arr[start:stop:step]




In [ ]:

arr = np.array([1, 2, 3, 4], dtype='f')

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


#COPY AND VIEW:
* copy() is not affected by changes in original array.
* view() is affected by changes in current array and vice versa.

How to know?
* Use the base attribute: x.base -> returns none if array owns the data. (copy)

